version: "3.9"
services:
  #configurations for react frontend
  frontend:
    build:
      context: ./my-app/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  #configurations for django backend
  backend:
    build:
      context: ./backend/backend/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    #must wait for db services to run before starting backend
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    
  #configurations for postgres db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: postgres
volumes:
 postgres_data: