# Generated by Django 4.1.3 on 2022-11-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bored_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('education', 'Education'), ('recreational', 'Recreational'), ('social', 'Social'), ('diy', 'DIY'), ('charity', 'Charity'), ('cooking', 'Cooking'), ('relaxation', 'Relaxation'), ('music', 'Music'), ('busywork', 'Busywork')], max_length=20)),
                ('participants', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
            ],
        ),
    ]
